-- Add SaaS admin user
-- This migration adds the developer as a SaaS admin user
-- Admin Email: rafa69lauri@gmail.com
--
-- INSTRUCTIONS:
-- 1. Call the asaas-create-checkout function once with admin email to get the user_id from logs
-- 2. Replace 'your-user-id-here' with the actual user_id from the logs
-- 3. Apply this migration

-- INSERT INTO public.saas_admin_users (user_id)
-- VALUES ('your-user-id-here')  -- Replace with actual user ID from function logs
-- ON CONFLICT (user_id) DO NOTHING;